apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    api:
      dashboard: true
    providers:
      kubernetesGateway:
        enabled: true
    ports:
      web:
        port: 8000
        exposedPort: 80
        protocol: TCP
      websecure:
        port: 8443
        exposedPort: 443
        protocol: TCP
    service:
      spec:
        # 1. Assign the exact static IP you want from your MetalLB pool
        loadBalancerIP: 10.10.10.195

        # 2. Recommended: Preserves the true client source IP in logs/rules
        externalTrafficPolicy: Local
