---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: portainer
spec:
  interval: 1h
  chart:
    spec:
      chart: portainer
      sourceRef:
        kind: HelmRepository
        name: portainer
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    service:
      type: ClusterIP
    ingress:
      enabled: true
      hosts:
        - host: "portainer.${SECRET_DOMAIN}"
          paths:
            - path: "/"
    image:
      tag: lts
    tls:
      force: true
