    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: portainer
      namespace: portainer
    spec:
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: internal
          namespace: kube-system
          sectionName: https
      hostnames:
        - "portainer.${SECRET_DOMAIN}"
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: portainer # Name of your backend Kubernetes Service
              namespace: portainer
              port: 9000
