---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kured
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kured
  values:
    configuration:
      # openSUSE MicroOS reboot sentinel path
      rebootSentinel: "/run/reboot-needed"

---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kured
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 6.1.0
  url: oci://ghcr.io/kubereboot/charts/kured
