---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium
spec:
  gatewayClassName: cilium
  listeners:
  - protocol: HTTP
    port: 80
    name: web
    allowedRoutes:
      namespaces:
        from: All
  - protocol: HTTPS
    port: 443
    name: websecure
    allowedRoutes:
      namespaces:
        from: All
    tls:
      certificateRefs:
        - kind: Secret
          name: ${SECRET_DOMAIN/./-}-production-tls
  addresses:
    - type: IPAddress
      value: "10.10.10.160"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
spec:
  parentRefs:
    - name: cilium
      namespace: network
      sectionName: web
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
