apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-pool
spec:
  addresses:
  - 10.10.10.190-10.10.10.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
