---
creation_rules:
  - path_regex: .*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr"
    encrypted_regex: "^(data|stringData)$"
stores:
  yaml:
    indent: 2
