---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 1h
  chart:
    spec:
      chart: authentik
      sourceRef:
        kind: HelmRepository
        name: authentik
  values:
    authentik:
      secret_key: env://AUTHENTIK_SECRET_KEY
      env:
        AUTHENTIK_SECRET_KEY:
          valueFrom:
            secretKeyRef:
              name: authentik
              key: secret_key

      # This sends anonymous usage-data, stack traces on errors and
      # performance data to sentry.io, and is fully opt-in
      error_reporting:
        enabled: true
      postgresql:
        host: file:///postgres-creds/host
        name: file:///postgres-creds/dbname
        user: file:///postgres-creds/username
        password: file:///postgres-creds/password
        port: file:///postgres-creds/port

    server:
      route:
        main:
          enabled: true
          hostnames: [ "authentik.${SECRET_DOMAIN}" ]
          parentRefs:
            - name: external
              namespace: kube-system
              sectionName: https

      ingress:
        # Specify kubernetes ingress controller class name
#        ingressClassName: nginx | traefik | kong
        enabled: false
#        hosts:
#          - authentik.domain.tld
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-postgres-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true
    worker:
      volumes:
        - name: postgres-creds
          secret:
            secretName: authentik-postgres-app
      volumeMounts:
        - name: postgres-creds
          mountPath: /postgres-creds
          readOnly: true

    postgresql:
      enabled: false
#      auth:
#        password: "ThisIsNotASecurePassword"
    redis:
      enabled: true
