---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: HelmRepository
    name: portainer
  values:
    route:
      dashboard:
        host:
          name: portainer.soybagel.com
          path: /
          pathType: PathPrefix
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
