# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:t6by5IEb8/oxrvrxefjNhDOtUMLqxwDgVCq+tOASQuw=,iv:/XIx88oQ2OJwVtocrzv9s0J4jfCHEbG3OwvTtdaKlAc=,tag:cBIRJzeiNdnaTimqt6R+Ow==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxL1VOTU9lZUFWa3FMb1ZJ
        aFlIeUQ5ZHo4Y09kcGxPM2thdDlUWmpBQjJzCmhBV2I5N2VzMFh3NUhwVU9aRU94
        RW1kSUc1cmxJSFN4dzdXR2tzd1lwZ1UKLS0tIFN6SnRUa2Qvenc0N3dTVzFXdGNj
        bXEyRjZNSjR5V3g2Mzl5VGVBbzBTYUEKWFUUhvo81nc8RHU1uRpnC9242SdMZQio
        Cf3+WXJ9NYuCwlTFntP1VxJCN4z7MzuqzruPZscf2pKHHAdDFReSmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-18T00:29:28Z"
  mac: ENC[AES256_GCM,data:MX4zfE5v5+usENt84SIauHarE3/6V+Y6U3OFLNyEqBHJiKBxj59kMvk33BWVFjAAHBx5P35OluJzPyvLMuOwFYoAqCDiMddNVWX0DHMhobRtDMVzgKKIrTgge2vvvM3cUzkHD3VjyA6iiXOWgK40+ZwQWpOSZbQta4ht7Bkn46s=,iv:ebDihPKXxKDZpT1vH4racyL2sJFyrhSE2aK9NR6Yfc4=,tag:imQQ2bIFnMQE3viS6V90OQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
