---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dex
components:
  - ../../components/common
resources:
  - ./namespace.yaml  # Needed first to allow for secrets to sync before build
  - ./dex/ks.yaml
