# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: grafana-admin-secret
  namespace: observability
stringData:
  admin-user: ENC[AES256_GCM,data:JDbXwzo=,iv:oHJd/0RUFalKtWp/PXgIU3fcPFUz9RFC2czLQw0iBZA=,tag:/ct6h3WQAt1EOkY1kIjiLQ==,type:str]
  admin-password: ENC[AES256_GCM,data:MJNKpJQrgf9lPBnIVWhX0tc51bZhDxtb,iv:X8glZ4TDCbHLdY0PMPIXC0SgYOwwtOT/PGu9+VgsQC8=,tag:AZMBvc4qU4tmoSvAhDmjyA==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZjBQQ2VoM3pNWWdtUVND
        akEvT2QrcDV1a2ZlcTk2bDhPMmR4OWgvYlM4ClM4VFdDQzNtM2dLODhRZ0pSa0FI
        MklYYjNFcVdUYVlwcWlqa2dhNzIwWU0KLS0tIDRxRkxONFgyZU1zNDVlUUVnd0ZD
        QWZaRDlWRWRzNEN6bkhES05YUUpObkkKvQfTLTjX+P4tWyICyuL8jErugWhfqpY9
        4fT+tk/tdf3Jbyh3U8tf/hsmcsxOB6DJWYHB5wnFo7S6VhF7RYFpxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-22T21:26:29Z"
  mac: ENC[AES256_GCM,data:FsnHBl819/aX03D2HXgNQjmXtGr3h/ykdSfHzF7gqoFzGTwPk2WotMLzL4UIQ7Nal0kKSBVjWdf52GkLN9dtJbYX/RwcJUhXmSrya+X2bwacAlb6MthOHCpsiCQLGrlUlJeaTOaOGxoH5/AzCE5c4//r8cFj4/qpXUjEwlipbEI=,iv:SLNnITJrCW+PhtnzsUqPHp8cBQSo+DeRkZnNFdWYwmk=,tag:AI2fJy+/H4xOh4DjurvIDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
