apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cnpg-longhorn
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "1"
  dataLocality: "strict"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
