apiVersion: v1
kind: Secret
metadata:
  name: backblaze-credentials
type: Opaque
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:ij4IC/Wwpw1G9FzsBnvFSuxjOeqYfsnAKQ==,iv:UaXGjqhH3ofv8EsgXmVNa7Skp65YDm5a8Y0BytLmw9w=,tag:8/BNHJvksiVVJYWqLtuN6g==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Q39dKdYx/BFIH2wwSsAM1yuoDQfRjMAPKg==,iv:s7WLD5LveXeMr8PgsLljbH7P8zEPxW2onSJmzmSw5k4=,tag:3SUlvwpmP+YyTgCiDmY9Cw==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:4SICMeW3+dSlRtTZuoMD0jynT3q7olZoy7vJP7GcaA==,iv:cwArlmvXCmRfjavdLZmOOdrZaHXmWRIExNsQDApU5mQ=,tag:GaFqOUUz82LxEbh+4qDN6g==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cl4VrxmwLxHBsaPbKdWX08djVWlbRLi4UHF9iepxTg==,iv:jQbhaJLbXb+mO4Z5qzyRsMKjl6DO4n9svZNb67iemvY=,tag:y+K/nR6Wian7yYzxbmhseg==,type:str]
  AWS_ENDPOINTS: ENC[AES256_GCM,data:kwgA0CfynFTiPhWVSwsKcA/prD3joAndjPpHBZMY+/SJYKmD2Ao=,iv:P0ajAC1EAJI4umd2JfU3GCmldzrkPKMVCV9fRUwWexQ=,tag:QDpNwaMoz8lwdfDEd0er+A==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK2x1YmdqZjBSWmc5Vnc2
        VlJPOGxJbFRkN0lNcEoxOE4zb2VuOVRYYmtJCkp0b1ZhbU1jaFVjS3NKMjRrNVls
        WVdSeXl2NnExSWZkNTV4dkd1MHB6VjgKLS0tIFg5VEkzNXJVclZnUFlna05tVmt1
        UXJyaGJKK1FCK01zbzhUWVV1cjcvaUkKtQnB5P1rOeaUiAQNdvW9BdBJgY+BKE45
        o4YUR2NvB1uO0yPVwOPbLXBvjHEhosJh0HT7KKbbiT1Zm63akZ/VDQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T22:04:20Z"
  mac: ENC[AES256_GCM,data:43vUUarDMY1g95Q9HECIG/DI6D9u16ekjkp2GrD3QZW53bKXQZKu6iec/mVDO0M7dnklVygwzsAZrxTZX2r7s1oUbacPegnuWmkIYVNoxVpL1KNPTHMCX29FqKCnSE+nKXaOwCCWddIbl+MHOCTWFNopa1LOmSfpCNLZJckH67w=,iv:RDrd61Q2z0zyjFtRr+PuBY2kyJYbvOzb/lbkIezL00U=,tag:mINDaE2Mt2SwjFICmGvhwA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
