apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-postgres
spec:
  instances: 3

  bootstrap:
    initdb:
      database: gitea
      owner: gitea
      localeCollate: 'en_US.UTF-8'
      localeCType: 'en_US.UTF-8'
      dataChecksums: true

  storage:
    size: 1Gi
    storageClass: local-path
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: backblaze-store
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: gitea-postgres-backup
spec:
  cluster:
    name: gitea-postgres
  schedule: '0 0 0 * * *'
  backupOwnerReference: self
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
