apiVersion: v1
kind: Secret
metadata:
  name: cloudflare
stringData:
  CF_API_EMAIL: ENC[AES256_GCM,data:jLdCc0LoU/gtrPtyzc+30NDKBDZ+,iv:ZnxZMbykkL8NCXJPf2lPTTda/bw0IBIASvV4jJOEl2o=,tag:1mil+NNq0/Kw6nodKNggmA==,type:str]
  CF_DNS_API_TOKEN: ENC[AES256_GCM,data:QtCWy7szLSH5jGBH4xR6PfwNDiqE1xRTMBBLIOqOrlnWnblT4mtZ8w==,iv:cYxZ2V+lId7CaUa+r/8BCcbncpB0pnXpAnkQ3JnYnEY=,tag:lPEmdmtr2WZ05yMxkXsAWA==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWEJobm8yc1NCY1JObUdo
        Z1hwVmlWQkxzam9XUEMrelBxUWxidmZXZWh3CmFKaTExVDlyUWpHZ1Azc1ZPYnFa
        cld6MnJUQUMyM2lzSDN5K3p3Sld3SHMKLS0tIC9EamFPVTFvVzFRVkk2Z3J3WlhQ
        VXFKZXVDRTAzWWlGTEhlS2oxWm03SVEKdVCGdGu/la4FtNdOm3yvE03Lq4vJJ93i
        Zw/R8yboNGTj/k7TsgY9aI2x4JdCZq2FQ/euXGWj63j/1+AtXR0izg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-12T00:17:05Z"
  mac: ENC[AES256_GCM,data:8RvBZN8Ba+/iTclIjCIO3PadB4byQ8HH2BtCkDAVDM+kBXKVBuxh7zL7NpCofPnMK3FoxfmkjiBPOuYRoioErqxYnV6/U9TDEAoSG69MTZrsGPKbhJY8rMu405JNIrsjeJ85qUmjzLcWgJAYmUIGRPo8dPMsqfcpBg/ZocPaG9E=,iv:g3Tud4rkD+Hep4ZuZg8nnK1Jy5ReEyGiyb+hEvrFm5k=,tag:uGM5mhigDbkxb04vWLaSHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
