---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
  values:
    envFrom:
      - secretRef:
          name: cloudflare
    service:
      spec:
        loadBalancerIP: "10.8.8.6"
    ingressRoute:
      dashboard:
        enabled: true
        matchRule: Host(`traefik.${SECRET_DOMAIN}`)
        entryPoints:
          - websecure
    providers:
      kubernetesIngress:
        enabled: true
      kubernetesIngressNginx:
        # -- Enable Kubernetes Ingress NGINX provider
        enabled: true

        # Namespace discovery
        # -- Namespace the controller watches for updates to Kubernetes objects
        # When using rbac.namespaced, it will watch helm release namespace and namespaces listed in this array
        # namespaces:
        #   - default
        # OR use namespace selector (mutually exclusive with namespaces)
        # namespaceSelector: "environment=production"

        # IngressClass configuration
        # -- Name of the ingress class this controller satisfies
        ingressClass: "nginx"
        # -- Ingress Class Controller value this controller satisfies
        controllerClass: "k8s.io/ingress-nginx"
        # -- Define if Ingress Controller should also watch for Ingresses without an IngressClass or the annotation specified
        watchIngressWithoutClass: false
        # -- Define if Ingress Controller should watch for Ingress Class by Name together with Controller Class
        ingressClassByName: false
#        ingressEndpoint:
#          # -- Hostname used for Kubernetes Ingress endpoints
#          hostname: "traefik.${SECRET_DOMAIN}"
#          # -- IP used for Kubernetes Ingress endpoints
#          ip: "10.8.8.6"
      kubernetesGateway:
        enabled: false
        statusAddress:
          ip: 10.8.8.6

    # Configure Network Ports and EntryPoints
    # EntryPoints are the network listeners for incoming traffic.
    ports:
      # Defines the HTTP entry point named 'web'
      web:
        port: 80
        nodePort: 30000
        # Instructs this entry point to redirect all traffic to the 'websecure' entry point
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
              permanent: true

      # Defines the HTTPS entry point named 'websecure'
      websecure:
        port: 443
        nodePort: 30001

    # Enables the dashboard in Secure Mode
    api:
      dashboard: true
      insecure: true

    # Enable persistence for ACME data (certificates, account) to ensure it survives pod restarts:
    persistence:
      enabled: true
      name: data

    certificatesResolvers:
      le:
        # Enable ACME (Let's Encrypt): automatic SSL.
        acme:

          # Email address used for registration.
          #
          # Required
          #
          email: "scottgorlin@gmail.com"

          # File or key used for certificates storage.
          #
          # Required
          #
          storage: "/data/acme.json"

          # Use a DNS-01 ACME challenge rather than HTTP-01 challenge.
          # Note: mandatory for wildcard certificate generation.
          dnsChallenge:
            provider: cloudflare
    deployment:
      initContainers:
        - name: volume-permissions  # https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md
          image: busybox:latest
          command: [ "sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json" ]
          volumeMounts:
            - mountPath: /data
              name: data
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
