# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZNt/qelTvaJmGrh+wX9Zr27MXc9KwNyIugLELQPcNciZQvaQgTutcw==,iv:jmtddR5ex2hBY6gmKP2TUR0d/RtKZufYBFWeVUdmbWg=,tag:iL7F7SlSa4iNiBx6B+8AYg==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNFJJRjlUWGNWM3Rqd1Zv
        MnpHZXdzajhxV2QvaU9QZEdleTJLMkhiRzFVCjJJaldBdElKSzlhd0hMRm4rbUta
        TVNQazRJVlNabU9WN1NmWUc1Z1RWWGcKLS0tIFF0R05NR1VSdjVEVjlUWEFmeDNt
        Smp2Tkx3SmpGOGN6RmFmVlM2cEtmM0UKkO9kSI4RaZhAy4lx16jjGe4etbbhRYZe
        SnsDQmCr5JJFbmqT9NBAL6WtGu8nP+fN2rtgFF5Xj+wB+NhxPmUhug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-18T00:29:28Z"
  mac: ENC[AES256_GCM,data:T6hosbRhz1RifCt12412Mx01EfX0HvSTbmjRyzs3DjUORXN6v2OKeFoVZ/t9fAEPWUdCErZYP22ddnUrNmki6vw2nx3uiqN3E1QoMw5mY/6+Pt3HaUP1hyXvsZN3kRPi8IObAIwELOudveR2YsJZD/KMup7SIxhdG4Ouek1gjkM=,iv:ZwPaRWKaB7NTe1neBu6mhqu9HtHwvgSyF5NQBkiEfZQ=,tag:1fuH/U9rS8kwQdN/xc/AMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
