# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.10.8:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.8.8.8"
  - "10.10.10.8"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

nodes:
  - hostname: "talos-1"
    ipAddress: "10.8.8.120"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/${pveSchematic}
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.8.8.8"
  - hostname: "talos-c1"
    ipAddress: "10.10.10.106"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/${pveSchematic}
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.10.10.8"
  - hostname: "talos-2"
    ipAddress: "10.8.8.127"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/${pveSchematic}
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.8.8.8"
  - hostname: "talos-c2"
    ipAddress: "10.10.10.109"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/${pveSchematic}
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.10.10.8"
  - hostname: "talos-3"
    ipAddress: "10.8.8.123"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/${pveSchematic}
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.8.8.8"
  - hostname: "talos-c3"
    ipAddress: "10.10.10.101"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/${pveSchematic}
    controlPlane: true
    networkInterfaces:
      - interface: ens18
        dhcp: true
        vip:
          ip: "10.10.10.8"
  - hostname: "talos-w1"
    ipAddress: "10.10.10.118"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/${pveSchematic}
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:cc:3f:12"
        dhcp: false
        addresses:
          - "10.8.8.118/16"
      - deviceSelector:
          hardwareAddr: "bc:24:11:6a:00:a5"
        dhcp: false
        mtu: 9000
        addresses:
          - "10.10.11.118/24"
      - deviceSelector:
          hardwareAddr: "bc:24:11:2a:38:98"
        dhcp: true
  - hostname: "talos-w2"
    ipAddress: "10.10.10.119"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/${pveSchematic}
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:3a:43:88"
        dhcp: false
        addresses:
          - "10.8.8.119/16"
      - deviceSelector:
          hardwareAddr: "bc:24:11:c3:46:2a"
        dhcp: false
        mtu: 9000
        addresses:
          - "10.10.11.119/24"
      - deviceSelector:
          hardwareAddr: "bc:24:11:f6:d0:d5"
        dhcp: true
  - hostname: "talos-w3"
    ipAddress: "10.10.10.112"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/${pveSchematic}
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:aa:d4:ce"
        dhcp: false
        addresses:
          - "10.8.8.112/16"
      - deviceSelector:
          hardwareAddr: "bc:24:11:bd:11:9a"
        dhcp: false
        mtu: 9000
        addresses:
          - "10.10.11.112/24"
      - deviceSelector:
          hardwareAddr: "bc:24:11:88:e4:96"
        dhcp: true
  - hostname: "talos-opti"
    ipAddress: "10.8.8.70"
    installDisk: /dev/sda
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/557e590213c3282421fd8a7df6825075bd17f119d805082e32d899bfba8e4646
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "98:b7:85:20:1e:fc"
        dhcp: true
      - deviceSelector:
          hardwareAddr: "98:b7:85:20:1e:fd"
        dhcp: false
        mtu: 9000
        addresses:
          - "10.10.11.70/24"
  - hostname: "talos-spare"
    ipAddress: "10.10.10.104"
    installDisk: /dev/sda
    machineSpec:
      secureboot: true
    talosImageURL: factory.talos.dev/installer-secureboot/${pveSchematic}
    controlPlane: false
    networkInterfaces:
      - interface: ens18
        dhcp: true

# Global patches
patches:
  - "@./patches/global/cilium.yaml"
  - "@./patches/global/cluster.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-kernel.yaml"
  - "@./patches/global/machine-files.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

# Worker patches
worker:
  userVolumes:
    - name: data
      provisioning:
        diskSelector:
          match: "!system_disk"
        minSize: 50GB
        maxSize: 400GB
        grow: true
#    - name: longhorn
#      provisioning:
#        diskSelector:
#          match: disk.transport == 'nvme'
#        minSize: 100GB
  patches:
    - "@./patches/worker/machine-kubelet.yaml"
