---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: local-path-storage
  namespace: local-path-storage
spec:
  interval: 60m
  url: https://github.com/rancher/local-path-provisioner.git
