# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: superset-env
stringData:
  REDIS_HOST: ENC[AES256_GCM,data:MLcdUzJ6JU9HAEfT4RZbi6ltyV9HCFI=,iv:4Hid/MiSZ+9Rli043Bg8S/LZS1kvhX7IQiAxbCQwn7w=,tag:mR6k/jhz9EtVnb+wSBPTAA==,type:str]
  REDIS_USER: ""
  REDIS_PORT: ENC[AES256_GCM,data:urrASA==,iv:cnbZqKl8cIIM51yoSrpA/vGtcE4XNNmb+MFu8+kk+2U=,tag:ru7VnQ9H2ulB3ufBbw8ulw==,type:str]
  REDIS_PROTO: ENC[AES256_GCM,data:1vMyiGU=,iv:154fUed0BsZSpNlTd5J+HPQ6/CZ0ot3BSnPanIwQUTw=,tag:7FxiT09Z+1BJygIe8sLdBA==,type:str]
  REDIS_DRIVER: ""
  REDIS_DB: ENC[AES256_GCM,data:vQ==,iv:wvwl3QaPDXIVXZ5qTVtgzLQn4WlJ0CMbPUk7kZvhW9g=,tag:6P9Q/mjZCnJLf/01VMH1hw==,type:str]
  REDIS_CELERY_DB: ENC[AES256_GCM,data:DQ==,iv:8n4Hy2owvI2SK+gUdhIhzQu666A6OjvNfxs3dMI98NA=,tag:W/MsCEQQl7+dsAsenlp0gQ==,type:str]
  SUPERSET_SECRET_KEY: ENC[AES256_GCM,data:VVfsqlZU5hS0x+S8hvaWY/ViwMIjR0yM2ZwxH6IWdbg=,iv:Y4ulrWq/lABLBC5Dim+MKLhboZ/HWsRS4qTinFmRMpg=,tag:L+BVgfE8bqADLpgyuxa6pA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjFFSlhXTCtiV21wZlZi
        Y3FlR0hFR2U0Zm5UTTRrckNHVzJVRlVmankwCkp0S0JvaFN2M2t3THM2NEk1cjV2
        V3RZY2VKcTRvdVNHZGRicTRzOUxSTDAKLS0tIHR5S2ZuelI5Tk43U1F2WXliWlJH
        UkR2a0dabmNScUIvb1dQdFBFRXJpekUKPAzw9kys6n3w/BMgF089HJf6KYlK44/X
        8Cvr1nXXncoKFV+oVnL1p46UdMaAJ06MOGNxqocJYCYQTv2hQkMbng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-06T03:47:56Z"
  mac: ENC[AES256_GCM,data:dnk/51phk89iq8+8mnUSUzImi6fac8isIUH2KmomHhULhoHqhqH5nRl9TUpA8zPe428pg5m0gvgpBKDQ0waNXKF9uz0Fh95Na+BP2Wit/RKW5tOJQM+NKBnob6lY5I1Cq93AJiZD31WH/7UtMoWa6+90a2jVZWMrwleMNluPAPQ=,iv:8Peh4mlNPVJNG6PKeXOSa15OfzL1Th0z8L3/8mf/eUI=,tag:rCb3iHnj1JFzKp8wDhUbSg==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
