apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rook-ceph-mgr-external
  labels:
    # Match the Prometheus Operator's serviceMonitorSelector label
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: http-external-metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - rook-ceph-pve
  selector:
    matchLabels:
      app: rook-ceph-mgr
      rook_cluster: rook-ceph-pve
---
apiVersion: v1
kind: Endpoints
metadata:
  name: rook-ceph-mgr-external
subsets:
  - addresses:
      - ip: "10.10.10.63"
      - ip: "10.10.10.64"
      - ip: "10.10.10.72"
    ports:
      - name: http-metrics
        port: 9283
        protocol: TCP
