---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app longhorn
  namespace: &namespace longhorn-system
spec:
  interval: 1h
  chart:
    spec:
      chart: longhorn
      version: 1.11.1
      sourceRef:
        kind: HelmRepository
        name: *app
  values:
    defaultSettings:
      defaultDataLocality: best-effort
      snapshotDataIntegrityImmediateCheckAfterSnapshotCreation: true
      snapshotDataIntegrity: enabled

    persistence:
      defaultDataLocality: best-effort

    ingress:
      enabled: false
#      ingressClassName: traefik
#      host: "longhorn.${SECRET_DOMAIN}"
#      annotations:
#        traefik.ingress.kubernetes.io/router.tls.certresolver: le
#        traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik@kubernetescrd

# Gateway routes available in 1.11.x chart, but unclear how to tie in with authentik forward auth
#    httproute:
#      enabled: true
#      parentRefs:
#        - group: gateway.networking.k8s.io
#          kind: Gateway
#          name: envoy-internal
#          namespace: network
#          sectionName: https
#      hostnames:
#        - "longhorn.${SECRET_DOMAIN}"

    metrics:
      serviceMonitor:
        enabled: true

---
# Route ALL longhorn traffic through the authentik proxy outpost
# The outpost itself handles checking auth and proxying forward
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: longhorn-httproute
  namespace: authentik  # note: in authentik namespace since that's where outpost lives
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      name: envoy-internal
      namespace: network
      sectionName: https
  hostnames:
    - "longhorn.${SECRET_DOMAIN}"
  rules:
    - backendRefs:
        - name: ak-outpost-authentik-embedded-outpost
          port: 9000
