apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily_snapshots
spec:
  cron: "40 6 * * *"
  task: "snapshot"
  groups:
  - default
  retain: 30

---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-system-backup
spec:
  task: system-backup
  cron: '45 7 */7 * *'
  retain: 12
  parameters:
    volume-backup-policy: if-not-present
