# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: superset-env
stringData:
  SUPERSET_SECRET_KEY: ENC[AES256_GCM,data:VVfsqlZU5hS0x+S8hvaWY/ViwMIjR0yM2ZwxH6IWdbg=,iv:Y4ulrWq/lABLBC5Dim+MKLhboZ/HWsRS4qTinFmRMpg=,tag:L+BVgfE8bqADLpgyuxa6pA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjFFSlhXTCtiV21wZlZi
        Y3FlR0hFR2U0Zm5UTTRrckNHVzJVRlVmankwCkp0S0JvaFN2M2t3THM2NEk1cjV2
        V3RZY2VKcTRvdVNHZGRicTRzOUxSTDAKLS0tIHR5S2ZuelI5Tk43U1F2WXliWlJH
        UkR2a0dabmNScUIvb1dQdFBFRXJpekUKPAzw9kys6n3w/BMgF089HJf6KYlK44/X
        8Cvr1nXXncoKFV+oVnL1p46UdMaAJ06MOGNxqocJYCYQTv2hQkMbng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T18:48:06Z"
  mac: ENC[AES256_GCM,data:2rDGsmvMk6jLU70HKClSEugmiuXGs8B+wtJL0z0V5UYdKlowLoPpTiIDydkhlodLU26RGKx1bWLa6h9Tm70abG95ShtXUO1xNYXjLfbGQD1qjD2O7lDfRXLgjY+ZQYq43a3MYXStbHd5CrDhDNaf8eugUcUaNoZyueMB04SUITI=,iv:OC9YbvK1cXr4Gcqfvk8RG1rYwt1gRe02WEUl23D+6/I=,tag:6TJ5utgOFPO0KgRpOw9wNQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
