# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: superset
stringData:
  secret_key: ENC[AES256_GCM,data:laCWMOQB4u0KXWbLgpV2yJmbCn7Rgler9U8+yVnjeVA=,iv:Zd1PZsos/iJrpYhJRIMmTJ1pYNqny1T1iH5sQM1qm1A=,tag:wzRHvjbYh/lUQeT1oXzpfA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWjFFSlhXTCtiV21wZlZi
        Y3FlR0hFR2U0Zm5UTTRrckNHVzJVRlVmankwCkp0S0JvaFN2M2t3THM2NEk1cjV2
        V3RZY2VKcTRvdVNHZGRicTRzOUxSTDAKLS0tIHR5S2ZuelI5Tk43U1F2WXliWlJH
        UkR2a0dabmNScUIvb1dQdFBFRXJpekUKPAzw9kys6n3w/BMgF089HJf6KYlK44/X
        8Cvr1nXXncoKFV+oVnL1p46UdMaAJ06MOGNxqocJYCYQTv2hQkMbng==
        -----END AGE ENCRYPTED FILE-----
      recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T17:52:45Z"
  mac: ENC[AES256_GCM,data:9/1nY/aP8SK3ykZNYdXPCJXEYB46chgB/5uVo6BmBLq9t2lDwKznz/p3csqX2u3iPMQrjoNvMWraaK7/QqQayz03iqdZPl23AdWR8ECwb5K8wp4p13UofhZmRDiBuZ7+VzKK5Iin8ElKtlsrMuti3MjC5dHJ+jLHogeepY51oW0=,iv:ybAlHTzLheGX4mkd0PuVzUfLNn0XnPGOWDmGBSc2vOU=,tag:eVtHujJoaZkojh+b0YYd2Q==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
