# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  # rook-ceph expects this name
  name: rook-ceph-dashboard-password
  namespace: rook-ceph
data:
  password: ENC[AES256_GCM,data:fpj7BIfRmkwALtkuYmEoE6uXmnuyQDnu,iv:1C8PM7OG5QkWHLGZrRKB+Us7UyBbkKpfD+UXhQpjr5s=,tag:7zQHxEp7j/greh/hJEr0Bw==,type:str]
sops:
  age:
    - recipient: age17my7ump8yjkqhdw7qcj8c54hn3xxxhlne2ssvk8arj3ladyqjyjq33uzzr
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZjBQQ2VoM3pNWWdtUVND
        akEvT2QrcDV1a2ZlcTk2bDhPMmR4OWgvYlM4ClM4VFdDQzNtM2dLODhRZ0pSa0FI
        MklYYjNFcVdUYVlwcWlqa2dhNzIwWU0KLS0tIDRxRkxONFgyZU1zNDVlUUVnd0ZD
        QWZaRDlWRWRzNEN6bkhES05YUUpObkkKvQfTLTjX+P4tWyICyuL8jErugWhfqpY9
        4fT+tk/tdf3Jbyh3U8tf/hsmcsxOB6DJWYHB5wnFo7S6VhF7RYFpxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-09-22T17:08:53Z"
  mac: ENC[AES256_GCM,data:xxo0vAM8nZf0QOX/oUe8Jgy4ce7Yp2axK8vlubH/5v94m21lqwOYUiQlGhftAFixDY/fPzuQraC4D7a9eQDjj0hF/YSPeR+JkZehnOD1RelCMZP4WfpkUg8c+XxMg4ZNxHzSSEl5M9TJLPJU5/t2uBUrNYLKuCtp/jZPA2ykYR4=,iv:x6vCOuWtGWLIcnwwULKqE8bxaUKWgg7AYp7exWMGHkQ=,tag:c9FPJAlnypNb4yuKAbuqTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
